/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin_base;

import connectivity.ConnectionProvider;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author rites
 */
public class ForgetPassword extends javax.swing.JFrame {
    String oldPassword,securityQuestion,email,answer;
    /**
     * Creates new form ForgetPassword
     */
    public ForgetPassword() {
        initComponents();
        clear();
        scallCross();
        scallBackground();
        //scallBackArt();
    }
    public final void scallCross()
    {
        ImageIcon icon=new ImageIcon("C:\\Users\\rites\\OneDrive\\Documents\\NetBeansProjects\\HostelManagementSystem\\src\\images\\Exit_big.png");
        Image img=icon.getImage();
        Image sImage=img.getScaledInstance(btnclose.getWidth(), btnclose.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon finalImage=new ImageIcon(sImage);
        btnclose.setIcon(finalImage);
    }
    public final void scallBackground()
    {
        ImageIcon icon=new ImageIcon("C:\\Users\\rites\\OneDrive\\Documents\\NetBeansProjects\\HostelManagementSystem\\src\\images\\solid_4.jpg");
        Image img=icon.getImage();
        Image sImage=img.getScaledInstance(lblbackground.getWidth(), lblbackground.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon finalImage=new ImageIcon(sImage);
        lblbackground.setIcon(finalImage);
    }
    public final void scallBackArt()
    {
        ImageIcon icon=new ImageIcon("C:\\Users\\rites\\OneDrive\\Documents\\NetBeansProjects\\HostelManagementSystem\\src\\images\\joy_1.png");
        Image img=icon.getImage();
        Image sImage=img.getScaledInstance(lblart.getWidth(), lblart.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon finalImage=new ImageIcon(sImage);
        lblart.setIcon(finalImage);
    }
    private void clear()
    {
        lblnotice.setText("Please Search your ID");
        btnvalidate.setVisible(false);
        lblthanks.setText("");
        lblart.setIcon(null);
        cmbquestion.setSelectedIndex(0);
    }
    private void getDataById()
    {
        String Id=txtid.getText();
        int counter=0;
        Connection con;
        try {
            con = ConnectionProvider.getCon();
            if(con==null)
            {
                return;
            }
            Statement st = con.createStatement();
            ResultSet rs;
            rs = st.executeQuery("select * from admin_details where admin_id="+Id);
            while (rs.next()) {
               counter++; 
               email=rs.getString(6);
               oldPassword=rs.getString(7);
               securityQuestion=rs.getString(13);
               answer=rs.getString(14);
            }
            if(counter==0)
            {
                Id=null;
                lblnotice.setText("Invalid ID");
                btnvalidate.setVisible(false);
            }
            else
            {
                counter=0;
                lblnotice.setText("You are good to go");
                btnvalidate.setVisible(true);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Invalid ID");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnclose = new javax.swing.JButton();
        lblhead = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        btnvalidate = new javax.swing.JButton();
        lblsecurity = new javax.swing.JLabel();
        cmbquestion = new javax.swing.JComboBox<>();
        lblanswer = new javax.swing.JLabel();
        txtanswer = new javax.swing.JTextField();
        lblemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblnotice = new javax.swing.JLabel();
        lblthanks = new javax.swing.JLabel();
        lblart = new javax.swing.JLabel();
        lblbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 60, 60));

        lblhead.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        lblhead.setText("forget password pannel");
        getContentPane().add(lblhead, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 330, 40));

        lblid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblid.setText("Enter ID");
        getContentPane().add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 30));

        txtid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 100, 30));

        btnvalidate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnvalidate.setText("Validate");
        btnvalidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvalidateActionPerformed(evt);
            }
        });
        getContentPane().add(btnvalidate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 90, 30));

        lblsecurity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblsecurity.setText("Security Question");
        getContentPane().add(lblsecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 130, 30));

        cmbquestion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbquestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Name of Your 1st School.", "what is your Favourate Color.", " ", " " }));
        cmbquestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbquestionMouseClicked(evt);
            }
        });
        getContentPane().add(cmbquestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 270, 30));

        lblanswer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblanswer.setText("Verify Answer");
        getContentPane().add(lblanswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 100, 30));

        txtanswer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtanswer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtanswerMouseClicked(evt);
            }
        });
        getContentPane().add(txtanswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 170, 30));

        lblemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblemail.setText("Email ID");
        getContentPane().add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 100, 30));

        txtemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 270, 30));

        btnsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 80, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 600, 10));

        lblnotice.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        lblnotice.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lblnotice, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 280, 30));

        lblthanks.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        lblthanks.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lblthanks, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 160, 30));
        getContentPane().add(lblart, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 210, 150));
        getContentPane().add(lblbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btncloseActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setBounds(250,170, 600, 400);
    }//GEN-LAST:event_formWindowOpened

    private void btnvalidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvalidateActionPerformed
      String emailid=txtemail.getText();
      if(emailid.equalsIgnoreCase(email)==false)
      {
          lblnotice.setText("Email id doesn't match");
          txtemail.requestFocus();
          return;
      }
      String question=(String)cmbquestion.getSelectedItem();
      String newAnsawer=txtanswer.getText();
      if(securityQuestion.equalsIgnoreCase(question))
      {
          if(answer.equalsIgnoreCase(newAnsawer))
          {
              scallBackArt();
              lblnotice.setText("Password= "+oldPassword);
              cmbquestion.setSelectedIndex(0);
              lblthanks.setText("Thank You.");
              txtanswer.setText("");
              txtemail.setText("");
              txtid.setText("");
              btnvalidate.setVisible(false);
          }
          else
              lblnotice.setText("Question and Answer Doesn't matched");
      }
      else
          lblnotice.setText("Question and Answer Doesn't matched");
          
    }//GEN-LAST:event_btnvalidateActionPerformed

    private void cmbquestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbquestionMouseClicked
        
    }//GEN-LAST:event_cmbquestionMouseClicked

    private void txtanswerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtanswerMouseClicked
        
    }//GEN-LAST:event_txtanswerMouseClicked

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        getDataById();
    }//GEN-LAST:event_btnsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnvalidate;
    private javax.swing.JComboBox<String> cmbquestion;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblanswer;
    private javax.swing.JLabel lblart;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblhead;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblnotice;
    private javax.swing.JLabel lblsecurity;
    private javax.swing.JLabel lblthanks;
    private javax.swing.JTextField txtanswer;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
