/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package admin_base;
import java.sql.Connection; 
import java.sql.PreparedStatement;
import connectivity.ConnectionProvider;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * @author Ritesh Singh(The Bad_Boy)
 */

public class SignUp extends javax.swing.JFrame {
    
    String id,fname,lname,gender,email,mobile,adhar,securityQuestion,answer,blood;
    File img_photo,img_adhar,img_sign;
    String password,conformPassword;
    /**
     * Creates new form SignUp
     */
    private void clearPersonal()
    {
        txtadhar.setText(null);
        adhar=null;
        txtfname.setText(null);
        fname=null;
        txtlname.setText(null);
        lname=null;
        txtmobile.setText(null);
        mobile=null;
        rdofemale.setSelected(false);
        rdomale.setSelected(false);
        gender=null;
        cmbBloodGroup.setSelectedIndex(0);
        ckbphoto.setSelected(false);
        ckbphoto.setVisible(false);
        img_photo=null;
        ckbadhar.setSelected(false);
        ckbadhar.setVisible(false);
        img_adhar=null;
        ckbsign.setSelected(false);
        ckbsign.setVisible(false);
        img_sign=null;
    }
    private void lock2()
    {
        txtanswer.setEditable(false);
        txtconformpassword.setEditable(false);
        txtpassword.setEditable(false);
        cmbquestion.setSelectedIndex(0);
        cmbquestion.setEditable(false);
    }
    private void unLock2()
    {
        txtanswer.setEditable(true);
        txtconformpassword.setEditable(true);
        txtpassword.setEditable(true);
        cmbquestion.setSelectedIndex(0);
        
    }
    public SignUp() {
        initComponents();
        scallBack_personal();
        scallBack_login();
        scallBackground();
        scallCross();
    }
    public final void scallCross()
    {
        ImageIcon icon=new ImageIcon("C:\\Users\\rites\\OneDrive\\Documents\\NetBeansProjects\\HostelManagementSystem\\src\\images\\Exit_big.png");
        Image img=icon.getImage();
        Image sImage=img.getScaledInstance(btnCross.getWidth(), btnCross.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon finalImage=new ImageIcon(sImage);
        btnCross.setIcon(finalImage);
    }
    public final void scallBackground()
    {
        ImageIcon icon=new ImageIcon("C:\\Users\\rites\\OneDrive\\Documents\\NetBeansProjects\\HostelManagementSystem\\src\\images\\solid_5.jpg");
        Image img=icon.getImage();
        Image sImage=img.getScaledInstance(lblbackground.getWidth(), lblbackground.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon finalImage=new ImageIcon(sImage);
        lblbackground.setIcon(finalImage);
    }
    public final void scallBack_login()
    {
        ImageIcon icon=new ImageIcon("C:\\Users\\rites\\OneDrive\\Documents\\NetBeansProjects\\HostelManagementSystem\\src\\images\\solid_3.jpg");
        Image img=icon.getImage();
        Image sImage=img.getScaledInstance(lblback_login.getWidth(), lblback_login.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon finalImage=new ImageIcon(sImage);
        lblback_login.setIcon(finalImage);
    }
    public final void scallBack_personal()
    {
        ImageIcon icon=new ImageIcon("C:\\Users\\rites\\OneDrive\\Documents\\NetBeansProjects\\HostelManagementSystem\\src\\images\\solid_3.jpg");
        Image img=icon.getImage();
        Image sImage=img.getScaledInstance(lblback_personal.getWidth(), lblback_personal.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon finalImage=new ImageIcon(sImage);
        lblback_personal.setIcon(finalImage);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cmbBloodGroup = new javax.swing.JComboBox<>();
        lblmobile3 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        lbllname = new javax.swing.JLabel();
        txtadhar = new javax.swing.JTextField();
        lblfname = new javax.swing.JLabel();
        lbladhar = new javax.swing.JLabel();
        rdofemale = new javax.swing.JRadioButton();
        rdomale = new javax.swing.JRadioButton();
        lblfname1 = new javax.swing.JLabel();
        lblmobile = new javax.swing.JLabel();
        lbladhar1 = new javax.swing.JLabel();
        lbladhar2 = new javax.swing.JLabel();
        btnsignature = new javax.swing.JButton();
        btnphoto = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnadhar = new javax.swing.JButton();
        lbladhar3 = new javax.swing.JLabel();
        ckbsign = new javax.swing.JCheckBox();
        ckbadhar = new javax.swing.JCheckBox();
        ckbphoto = new javax.swing.JCheckBox();
        txtlname = new javax.swing.JTextField();
        txtmobile = new javax.swing.JTextField();
        lblback_personal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmbquestion = new javax.swing.JComboBox<>();
        lblmobile1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblmobile2 = new javax.swing.JLabel();
        txtanswer = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        btnsignup = new javax.swing.JButton();
        txtconformpassword = new javax.swing.JPasswordField();
        lble2 = new javax.swing.JLabel();
        lble1 = new javax.swing.JLabel();
        lble3 = new javax.swing.JLabel();
        lblback_login = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        btnvalodate = new javax.swing.JButton();
        btnCross = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblnotice1 = new javax.swing.JLabel();
        lblbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel1FocusLost(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbBloodGroup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbBloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "A+", "B+", "O+", "AB+", "A-", "B-", "O-", "AB-", " ", " " }));
        cmbBloodGroup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbBloodGroupFocusGained(evt);
            }
        });
        cmbBloodGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbBloodGroupMouseClicked(evt);
            }
        });
        jPanel1.add(cmbBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 170, 30));

        lblmobile3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblmobile3.setText("Blood Group");
        jPanel1.add(lblmobile3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 100, 30));

        txtfname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtfname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfnameFocusLost(evt);
            }
        });
        txtfname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfnameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtfnameMouseEntered(evt);
            }
        });
        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 170, 30));

        lbllname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbllname.setText("Last Name");
        jPanel1.add(lbllname, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 80, 30));

        txtadhar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtadhar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtadharFocusLost(evt);
            }
        });
        txtadhar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtadharMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtadharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtadharMouseExited(evt);
            }
        });
        jPanel1.add(txtadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 160, 30));

        lblfname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblfname.setText("First Name");
        jPanel1.add(lblfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 80, 30));

        lbladhar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbladhar.setText("Upload Signature");
        jPanel1.add(lbladhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 130, 30));

        buttonGroup1.add(rdofemale);
        rdofemale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdofemale.setText("Female");
        rdofemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdofemaleActionPerformed(evt);
            }
        });
        jPanel1.add(rdofemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, 30));

        buttonGroup1.add(rdomale);
        rdomale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdomale.setText("Male");
        rdomale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdomaleActionPerformed(evt);
            }
        });
        jPanel1.add(rdomale, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 70, 30));

        lblfname1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblfname1.setText("Select Gender");
        jPanel1.add(lblfname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 100, 30));

        lblmobile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblmobile.setText("Mobile Number");
        jPanel1.add(lblmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 110, 30));

        lbladhar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbladhar1.setText("Upload Photo");
        jPanel1.add(lbladhar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 110, 30));

        lbladhar2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbladhar2.setText("Adhar Number");
        jPanel1.add(lbladhar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 110, 30));

        btnsignature.setText("Browse");
        btnsignature.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnsignature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignatureActionPerformed(evt);
            }
        });
        jPanel1.add(btnsignature, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 130, 30));

        btnphoto.setText("Browse");
        btnphoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnphoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphotoActionPerformed(evt);
            }
        });
        jPanel1.add(btnphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 130, 30));

        btnclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclear.setText("Clear Details");
        btnclear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 260, 30));

        btnadhar.setText("Browse");
        btnadhar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnadhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadharActionPerformed(evt);
            }
        });
        jPanel1.add(btnadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 130, 30));

        lbladhar3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbladhar3.setText("Upload Adhar");
        jPanel1.add(lbladhar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 110, 30));

        ckbsign.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ckbsign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbsignActionPerformed(evt);
            }
        });
        jPanel1.add(ckbsign, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, -1, -1));

        ckbadhar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ckbadhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbadharActionPerformed(evt);
            }
        });
        jPanel1.add(ckbadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, -1, -1));

        ckbphoto.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ckbphoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbphotoActionPerformed(evt);
            }
        });
        jPanel1.add(ckbphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, -1, -1));

        txtlname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 160, 30));

        txtmobile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtmobile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtmobileMouseClicked(evt);
            }
        });
        jPanel1.add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 160, 30));
        jPanel1.add(lblback_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 300));

        jTabbedPane1.addTab("Personal Details", jPanel1);

        jPanel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel2FocusLost(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbquestion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbquestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Name of Your 1st School.", "what is your Favourate Color.", " ", " " }));
        cmbquestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbquestionMouseClicked(evt);
            }
        });
        jPanel2.add(cmbquestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 270, 30));

        lblmobile1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblmobile1.setText("Security Question");
        jPanel2.add(lblmobile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Set Answer");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 100, 30));

        lblmobile2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblmobile2.setText("Email ID");
        jPanel2.add(lblmobile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 100, 30));

        txtanswer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtanswer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtanswerMouseClicked(evt);
            }
        });
        jPanel2.add(txtanswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 170, 30));

        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpasswordMouseClicked(evt);
            }
        });
        jPanel2.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 170, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Enter Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 120, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Conform Password");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, 30));

        txtemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 270, 30));

        btnsignup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsignup.setText("Sign-Up");
        btnsignup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        jPanel2.add(btnsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 310, 30));

        txtconformpassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtconformpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtconformpasswordMouseClicked(evt);
            }
        });
        txtconformpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconformpasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtconformpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 170, 30));

        lble2.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        lble2.setForeground(new java.awt.Color(255, 0, 0));
        lble2.setText("jLabel2");
        jPanel2.add(lble2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 220, -1));

        lble1.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        lble1.setForeground(new java.awt.Color(255, 0, 0));
        lble1.setText("jLabel2");
        jPanel2.add(lble1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 260, -1));

        lble3.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        lble3.setForeground(new java.awt.Color(255, 0, 0));
        lble3.setText("jLabel2");
        jPanel2.add(lble3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 220, -1));
        jPanel2.add(lblback_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 300));

        jTabbedPane1.addTab("Login Details", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 800, 320));

        lblid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblid.setText("Enter Admin ID");
        getContentPane().add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 30));

        txtid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtidFocusLost(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 100, 30));

        btnvalodate.setText("Validate ID");
        btnvalodate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnvalodate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvalodateActionPerformed(evt);
            }
        });
        getContentPane().add(btnvalodate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 100, 30));

        btnCross.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrossActionPerformed(evt);
            }
        });
        getContentPane().add(btnCross, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 70, 60));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setText("admin sign-up form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 260, 60));

        lblnotice1.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        lblnotice1.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lblnotice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 390, 30));

        lblbackground.setText("lblbackground");
        getContentPane().add(lblbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsignatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignatureActionPerformed
        if(ckbadhar.isSelected()==false)
        {
            lblnotice1.setText("Please Choose Adhar Card");
            btnadhar.requestFocus();
            return;
        }
        
        //For Signature
        JFileChooser jfc=new JFileChooser();
        jfc.showOpenDialog(null);
        img_sign=jfc.getSelectedFile();
        if(img_sign==null)
        {
            JOptionPane.showMessageDialog(null, "Please! select a File");
            return;
        }
        boolean b2=validator.Validator.validatePhoto(img_sign);
        if(b2==false)
        {
            lblnotice1.setText("File Format not Supported");
            img_sign=null;
            ckbsign.setVisible(false);
            ckbsign.setSelected(false);
            ckbsign.requestFocus();
            
        }
        if(img_sign!=null)
        {
            ckbsign.setVisible(true);
            ckbsign.setSelected(true);
            lblnotice1.setText("");
        }
    }//GEN-LAST:event_btnsignatureActionPerformed

    private void txtidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidFocusLost

    }//GEN-LAST:event_txtidFocusLost

    private void rdofemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdofemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdofemaleActionPerformed

    private void rdomaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdomaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdomaleActionPerformed

    private void btnvalodateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvalodateActionPerformed
        String tempid;
        int i=0;
        tempid=txtid.getText();
        if(tempid.length()<4)
        {
            lblnotice1.setText("Invalid ID");
            txtid.requestFocus();
            return;
        }
        Connection con=ConnectionProvider.getCon();
        if(con==null)
        {
            return;
        }
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs=st.executeQuery("select * from admin_details where admin_id="+tempid);
            while(rs.next())
            {
                i++;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        if(i>=1)
        {
            lblnotice1.setText("Sorry! this ID is already Taken.");
            lblnotice1.setVisible(true);
            txtid.requestFocus();
        }
        else
        {
            lblnotice1.setText("You are Good To go");
            lblnotice1.setVisible(true);
            id=txtid.getText();
            txtfname.requestFocus();
        }
    }//GEN-LAST:event_btnvalodateActionPerformed

    private void btnphotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphotoActionPerformed
        //Adhar Validation
        boolean b=validator.Validator.validateAdhar(txtadhar.getText());
        if(txtadhar.getText().length()==0)
        {
            lblnotice1.setText("Please Fill your Adhar Number");
            txtadhar.requestFocus();
            return;
        }
        else if(b==false)
        {
            lblnotice1.setText("Adhar number Should be of 12 Digits only.");
            txtadhar.requestFocus();
            return;
        }
        else{
            
            adhar=txtadhar.getText();
            lblnotice1.setText("");
        }
        
        //For Photograph
        JFileChooser jfc=new JFileChooser();
        jfc.showOpenDialog(null);
        img_photo=jfc.getSelectedFile();
        if(img_photo==null)
        {
            JOptionPane.showMessageDialog(null, "Please! select a Image File");
            return;
        }
        boolean b2=validator.Validator.validatePhoto(img_photo);
        if(b2==false)
        {
            lblnotice1.setText("File Format not Supported");
            img_photo=null;
            ckbphoto.setVisible(false);
            ckbphoto.setSelected(false);
            btnphoto.requestFocus();
            
        }
        if(img_photo!=null)
        {
            ckbphoto.setVisible(true);
            ckbphoto.setSelected(true);
            lblnotice1.setText("");
        }
    }//GEN-LAST:event_btnphotoActionPerformed

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
        if(img_adhar==null || img_photo==null || img_sign==null)
        {
            lblnotice1.setText("Please Select Photo, Adhar and Signature");
            return;
        }
        if(password.equals(txtconformpassword.getText())==false)
        {
            
            lble3.setText("Password Does'n Match");
            lblnotice1.setText("");
            lble3.setVisible(true);
            return;
        }
        Connection con; 
        try{
            con=ConnectionProvider.getCon();
            if(con==null)
            {
            return;
            }
            
            PreparedStatement pst=con.prepareStatement("insert into admin_details values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, id);
            pst.setString(2,txtfname.getText());
            pst.setString(3,txtlname.getText());
            pst.setString(4,gender);
            pst.setString(5,blood);
            pst.setString(6,email);
            pst.setString(7,password);
            pst.setString(8,mobile);
            pst.setString(9,adhar);
            FileInputStream adharStream=new FileInputStream(img_adhar);
            pst.setBinaryStream(10, adharStream);
            FileInputStream PhotoStream=new FileInputStream(img_photo);
            pst.setBinaryStream(11, PhotoStream);
            FileInputStream signStream=new FileInputStream(img_sign);
            pst.setBinaryStream(12, signStream);
            pst.setString(13, securityQuestion);
            pst.setString(14, answer);
            pst.setString(15, "Not Allowed");
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Admin Details Saved Successfully");
            this.setVisible(false);
            new Login().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnsignupActionPerformed

    private void btnCrossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrossActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCrossActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setBounds(220, 95, 800, 475);
        lble1.setVisible(false);
        lble2.setVisible(false);
        lble3.setVisible(false);
        ckbadhar.setVisible(false);
        ckbphoto.setVisible(false);
        ckbsign.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        clearPersonal();
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnadharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadharActionPerformed
        if(ckbphoto.isSelected()==false)
        {
            lblnotice1.setText("Please Choose Photograph");
            btnphoto.requestFocus();
            return;
        }
        
        //For Adhar
        JFileChooser jfc=new JFileChooser();
        jfc.showOpenDialog(null);
        img_adhar=jfc.getSelectedFile();
        if(img_adhar==null)
        {
            JOptionPane.showMessageDialog(null, "Please! select a File");
            return;
        }
        boolean b2=validator.Validator.validatePhoto(img_adhar);
        if(b2==false)
        {
            lblnotice1.setText("File Format not Supported");
            img_adhar=null;
            ckbadhar.setVisible(false);
            ckbadhar.setSelected(false);
            ckbadhar.requestFocus();
            
        }
        if(img_photo!=null)
        {
            ckbadhar.setVisible(true);
            ckbadhar.setSelected(true);
            lblnotice1.setText("");
        }
    }//GEN-LAST:event_btnadharActionPerformed

    private void ckbsignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbsignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbsignActionPerformed

    private void ckbadharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbadharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbadharActionPerformed

    private void ckbphotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbphotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbphotoActionPerformed

    private void cmbBloodGroupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbBloodGroupFocusGained
        
    }//GEN-LAST:event_cmbBloodGroupFocusGained

    private void txtfnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfnameMouseEntered
        
    }//GEN-LAST:event_txtfnameMouseEntered

    private void txtfnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfnameMouseClicked
        if(id==null)
        {
           lblnotice1.setText("Please validate Your ID");
           btnvalodate.requestFocus();
           
        }
    }//GEN-LAST:event_txtfnameMouseClicked

    private void txtlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlnameActionPerformed

    private void txtmobileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmobileMouseClicked
        if(cmbBloodGroup.getSelectedIndex()==0)
        {
            lblnotice1.setText("Please select your blood Group");
            cmbBloodGroup.requestFocus();
        }else{
            lblnotice1.setText("");
            blood=(String)cmbBloodGroup.getSelectedItem();
        }
    }//GEN-LAST:event_txtmobileMouseClicked

    private void cmbBloodGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbBloodGroupMouseClicked
        if(rdomale.isSelected()==true)
        {
            gender="Male";
            lblnotice1.setText(""); 
        }
        else if(rdofemale.isSelected()==true)
        {
            gender="Female";
            lblnotice1.setText(""); 
        }
        else
        {
          lblnotice1.setText("Please Select Gender"); 
          rdomale.requestFocus();
        }
    }//GEN-LAST:event_cmbBloodGroupMouseClicked

    private void txtadharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtadharMouseClicked
        boolean b=validator.Validator.validateMobile(txtmobile.getText());
        if(txtmobile.getText().length()==0)
        {
            lblnotice1.setText("Please Fill your Mobile Number");
            txtmobile.requestFocus();
        }
        else if(b==false)
        {
            lblnotice1.setText("Mobile number Should be of 10 Digits only.");
            txtmobile.requestFocus();
        }
        else{mobile=txtmobile.getText();
            lblnotice1.setText("");
        }
        
    }//GEN-LAST:event_txtadharMouseClicked

    private void txtadharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtadharMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadharMouseEntered

    private void txtadharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtadharMouseExited
        
    }//GEN-LAST:event_txtadharMouseExited

    private void txtadharFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtadharFocusLost
       
    }//GEN-LAST:event_txtadharFocusLost

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
       
        
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jPanel2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2FocusLost
        
    }//GEN-LAST:event_jPanel2FocusLost

    private void jPanel1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusLost
        if(ckbphoto.isSelected()==false)
        {
            JOptionPane.showMessageDialog(null, "Please Insert Photograph");
            
        }
        else if(ckbadhar.isSelected()==false)
        {
            JOptionPane.showMessageDialog(null, "Please Insert Adhar");
            
        }
        else if(ckbsign.isSelected()==false)
        {
            JOptionPane.showMessageDialog(null, "Please Insert Signature");
            
        }
    }//GEN-LAST:event_jPanel1FocusLost

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        
    }//GEN-LAST:event_txtfnameActionPerformed

    private void txtfnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfnameFocusLost
        if(txtfname.getText().length()>2)
        {
        txtlname.requestFocus();
        }
    }//GEN-LAST:event_txtfnameFocusLost

    private void cmbquestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbquestionMouseClicked
        boolean b;
        b=validator.Validator.validateEmail(txtemail.getText());
        if(b)
        {
            lblnotice1.setText("Your Email is Valid, Go On..");
            email=txtemail.getText();
            unLock2();
            
        }
        else{
            lblnotice1.setText("Invalid Email");
            txtemail.requestFocus();
            lock2();
        }
    }//GEN-LAST:event_cmbquestionMouseClicked

    private void txtanswerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtanswerMouseClicked
        if(cmbquestion.getSelectedIndex()!=0)
        {
            securityQuestion=(String)cmbquestion.getSelectedItem();
        }
        else{
            lblnotice1.setText("Select Security Question");
            cmbquestion.requestFocus();
        }
    }//GEN-LAST:event_txtanswerMouseClicked

    private void txtpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpasswordMouseClicked
        lble3.setVisible(false);
        if(txtanswer.getText().length()>0)
        {
            answer=txtanswer.getText();
        }
        else
        {
            lblnotice1.setText("Please fill the Answer");
            txtanswer.requestFocus();
        }
    }//GEN-LAST:event_txtpasswordMouseClicked

    private void txtconformpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtconformpasswordMouseClicked
       boolean b;
        b=validator.Validator.validateStrongPassword(txtpassword.getText());
        if(b)
        {
            password=txtpassword.getText();
            lble1.setText("");
            lble2.setText("");
            lble3.setText("");
        }
        else{
            lblnotice1.setText("Invalid Password");
            lble1.setText("Password shuld have one uppercase & lowercase ");
            lble2.setText("A digit & a special character");
            lble3.setText("length between 6 to 15");
            lble1.setVisible(true);
            lble2.setVisible(true);
            lble3.setVisible(true);
            txtpassword.requestFocus();
        } 
    }//GEN-LAST:event_txtconformpasswordMouseClicked

    private void txtconformpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconformpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconformpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCross;
    private javax.swing.JButton btnadhar;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnphoto;
    private javax.swing.JButton btnsignature;
    private javax.swing.JButton btnsignup;
    private javax.swing.JButton btnvalodate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox ckbadhar;
    private javax.swing.JCheckBox ckbphoto;
    private javax.swing.JCheckBox ckbsign;
    private javax.swing.JComboBox<String> cmbBloodGroup;
    private javax.swing.JComboBox<String> cmbquestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbladhar;
    private javax.swing.JLabel lbladhar1;
    private javax.swing.JLabel lbladhar2;
    private javax.swing.JLabel lbladhar3;
    private javax.swing.JLabel lblback_login;
    private javax.swing.JLabel lblback_personal;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JLabel lble1;
    private javax.swing.JLabel lble2;
    private javax.swing.JLabel lble3;
    private javax.swing.JLabel lblfname;
    private javax.swing.JLabel lblfname1;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lbllname;
    private javax.swing.JLabel lblmobile;
    private javax.swing.JLabel lblmobile1;
    private javax.swing.JLabel lblmobile2;
    private javax.swing.JLabel lblmobile3;
    private javax.swing.JLabel lblnotice1;
    private javax.swing.JRadioButton rdofemale;
    private javax.swing.JRadioButton rdomale;
    private javax.swing.JTextField txtadhar;
    private javax.swing.JTextField txtanswer;
    private javax.swing.JPasswordField txtconformpassword;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
