package payment;

import connectivity.ConnectionProvider;
import home.HomePage;
import java.awt.Image;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.time.temporal.ChronoUnit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rites
 */
public class PaymentSystem extends javax.swing.JFrame {
    
    int security,months,paidmonths;
    String dues,id,name,father,nextmonth,currentmonth;
    /**
     * Creates new form PaymentSystem
     */
    private void lock()
    {
        txtfather.setEditable(false);
        txtfees.setEditable(false);
        txtmonths.setEditable(false);
        txtname.setEditable(false);
        txtpaidmonth.setEditable(false);
        txtsecurity.setEditable(false);
        txttotalamount.setEditable(false);
        txttotalfees.setEditable(false);
        txtuptomonth.setEditable(false);
    }
    private void clear()
    {
        txtfather.setText(null);
        txtfees.setText(null);
        txtmonths.setText(null);
        txtname.setText(null);
        txtpaidmonth.setText(null);
        txtsecurity.setText(null);
        txttotalamount.setText(null);
        txttotalfees.setText(null);
        txtuptomonth.setText(null);
        jdcmonth.setDate(null);
    }
    public PaymentSystem() {
        initComponents();
        scallBackground();
        scallCross();
    }
    public final void scallCross()
    {
        ImageIcon icon=new ImageIcon("C:\\Users\\rites\\OneDrive\\Documents\\NetBeansProjects\\HostelManagementSystem\\src\\images\\Exit_big.png");
        Image img=icon.getImage();
        Image sImage=img.getScaledInstance(btnexit.getWidth(), btnexit.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon finalImage=new ImageIcon(sImage);
        btnexit.setIcon(finalImage);
    }
    public final void scallBackground()
    {
        ImageIcon icon=new ImageIcon("C:\\Users\\rites\\OneDrive\\Documents\\NetBeansProjects\\HostelManagementSystem\\src\\images\\solid_5.jpg");
        Image img=icon.getImage();
        Image sImage=img.getScaledInstance(lblbackground.getWidth(), lblbackground.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon finalImage=new ImageIcon(sImage);
        lblbackground.setIcon(finalImage);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblhead = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        lblid = new javax.swing.JLabel();
        btnMakepayment = new javax.swing.JButton();
        btnFetch = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        txttotalfees = new javax.swing.JTextField();
        lblroomno4 = new javax.swing.JLabel();
        txtsecurity = new javax.swing.JTextField();
        ckbsecurity = new javax.swing.JCheckBox();
        lblroomno7 = new javax.swing.JLabel();
        lblroomno8 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblroomno9 = new javax.swing.JLabel();
        txtfather = new javax.swing.JTextField();
        lblroomno10 = new javax.swing.JLabel();
        txtmonths = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblroomno11 = new javax.swing.JLabel();
        txtuptomonth = new javax.swing.JTextField();
        lbluptomonth = new javax.swing.JLabel();
        jdcmonth = new com.toedter.calendar.JDateChooser();
        btnedit1 = new javax.swing.JButton();
        txtpaidmonth = new javax.swing.JTextField();
        lblroomno12 = new javax.swing.JLabel();
        txtfees = new javax.swing.JTextField();
        lblroomno13 = new javax.swing.JLabel();
        txttotalamount = new javax.swing.JTextField();
        lblroomno14 = new javax.swing.JLabel();
        btncalculate = new javax.swing.JButton();
        btngeneraterecipt = new javax.swing.JButton();
        lblbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhead.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        lblhead.setText("welcome to the payment getway system");
        getContentPane().add(lblhead, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 540, 40));

        txtid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 100, 30));

        lblid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblid.setText("Enter ID");
        getContentPane().add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, 30));

        btnMakepayment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMakepayment.setText("Make Payment");
        btnMakepayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakepaymentActionPerformed(evt);
            }
        });
        getContentPane().add(btnMakepayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 370, 30));

        btnFetch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFetch.setText("Fetch Details");
        btnFetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFetchActionPerformed(evt);
            }
        });
        getContentPane().add(btnFetch, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 150, 30));

        btnreset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        getContentPane().add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, 30));

        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 70, 60));

        txttotalfees.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txttotalfees, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 120, 30));

        lblroomno4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblroomno4.setText("Security Money");
        getContentPane().add(lblroomno4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 130, 30));

        txtsecurity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtsecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 120, 30));

        ckbsecurity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ckbsecurity.setText("paid");
        getContentPane().add(ckbsecurity, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        lblroomno7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblroomno7.setText("Student Name:");
        getContentPane().add(lblroomno7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, 30));

        lblroomno8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblroomno8.setText("Total fees Dues");
        getContentPane().add(lblroomno8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 120, 30));

        txtname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 140, 30));

        lblroomno9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblroomno9.setText("Select Month to pay");
        getContentPane().add(lblroomno9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 170, 30));

        txtfather.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtfather, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 140, 30));

        lblroomno10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblroomno10.setText("Father's Name");
        getContentPane().add(lblroomno10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 110, 30));

        txtmonths.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtmonths, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 80, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 800, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 800, 10));

        lblroomno11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblroomno11.setText("Number of Months");
        getContentPane().add(lblroomno11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 140, 30));

        txtuptomonth.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtuptomonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 90, 30));

        lbluptomonth.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbluptomonth.setText("Paid UpTo");
        getContentPane().add(lbluptomonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 110, 30));
        getContentPane().add(jdcmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 130, 30));

        btnedit1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnedit1.setText("Edit Profile");
        btnedit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnedit1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnedit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 110, 30));

        txtpaidmonth.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtpaidmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 90, 30));

        lblroomno12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblroomno12.setText("No. of Months selected");
        getContentPane().add(lblroomno12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 170, 30));

        txtfees.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtfees, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 100, 30));

        lblroomno13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblroomno13.setText("monthly Fees");
        getContentPane().add(lblroomno13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 110, 30));

        txttotalamount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txttotalamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 90, 30));

        lblroomno14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblroomno14.setText("Total Amount");
        getContentPane().add(lblroomno14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 110, 30));

        btncalculate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncalculate.setText("Calculate");
        btncalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalculateActionPerformed(evt);
            }
        });
        getContentPane().add(btncalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 110, 30));

        btngeneraterecipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btngeneraterecipt.setText("Generate Recipt");
        btngeneraterecipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngeneratereciptActionPerformed(evt);
            }
        });
        getContentPane().add(btngeneraterecipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 370, 30));
        getContentPane().add(lblbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setBounds(170,150, 800, 500);
    }//GEN-LAST:event_formWindowOpened

    private void btnMakepaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakepaymentActionPerformed
    try {
            Connection con1=ConnectionProvider.getCon();
            PreparedStatement pst=con1.prepareStatement("update fees set paidUpTo=? where id="+id);
            pst.setString(1, nextmonth);
            pst.executeUpdate();
            clear();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_btnMakepaymentActionPerformed

    private void btnFetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFetchActionPerformed
        id=txtid.getText();
        boolean b=true;
        try {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from fees where id="+id);
            while(rs.next())
            {
                b=false;
                security=rs.getInt(2);
                currentmonth=rs.getString(4);
                long monthsBetween = ChronoUnit.MONTHS.between(LocalDate.parse(currentmonth).withDayOfMonth(1),LocalDate.now().withDayOfMonth(1));
                months=(int)monthsBetween;
                LocalDate paidUpTo= LocalDate.parse(rs.getString(4));
                Month month = paidUpTo.getMonth();
                int year = paidUpTo.getYear();
                txtuptomonth.setText(""+month+" "+year);
                if(months==0)
                {
                    dues="No";
                    JOptionPane.showMessageDialog(null,"You dont Have any pending Dues");
                    return;
                }
                else
                {
                    txttotalfees.setText(""+(security*months));
                    txtmonths.setText(""+months);
                    txtsecurity.setText(""+security);
                    ckbsecurity.setSelected(true);
                }
            }
            Connection con1=ConnectionProvider.getCon();
            Statement st1=con1.createStatement();
            ResultSet rs1=st1.executeQuery("select * from admission where std_id="+id);
            while(rs1.next())
            {
                name=rs1.getString(2)+" "+rs1.getString(3);
                father=rs1.getString(6);
                txtname.setText(name);
                txtfather.setText(father);
            }
            lock();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
          }
        if(b)
        {
            JOptionPane.showMessageDialog(null,"Invalid Id");
            b=true;
            return;
        }
    }//GEN-LAST:event_btnFetchActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        HomePage.payment=true;
        setVisible(false);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnedit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnedit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnedit1ActionPerformed

    private void btncalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalculateActionPerformed
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        if(jdcmonth.getDate()==null)
        {
            JOptionPane.showMessageDialog(null, "Please select month For the payment");
            return;
        }
        else
        {
            nextmonth=sdf.format(jdcmonth.getDate());
            long monthsBetween = ChronoUnit.MONTHS.between(LocalDate.parse(currentmonth).withDayOfMonth(1),LocalDate.parse(nextmonth).withDayOfMonth(1));
            paidmonths=(int)monthsBetween;
            txtpaidmonth.setText(""+paidmonths);
            txtfees.setText(""+security);
            txttotalamount.setText(""+(paidmonths*security));
        }
        
    }//GEN-LAST:event_btncalculateActionPerformed

    private void btngeneratereciptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngeneratereciptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btngeneratereciptActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
    clear();
    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFetch;
    private javax.swing.JButton btnMakepayment;
    private javax.swing.JButton btncalculate;
    private javax.swing.JButton btnedit1;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btngeneraterecipt;
    private javax.swing.JButton btnreset;
    private javax.swing.JCheckBox ckbsecurity;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private com.toedter.calendar.JDateChooser jdcmonth;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JLabel lblhead;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblroomno10;
    private javax.swing.JLabel lblroomno11;
    private javax.swing.JLabel lblroomno12;
    private javax.swing.JLabel lblroomno13;
    private javax.swing.JLabel lblroomno14;
    private javax.swing.JLabel lblroomno4;
    private javax.swing.JLabel lblroomno7;
    private javax.swing.JLabel lblroomno8;
    private javax.swing.JLabel lblroomno9;
    private javax.swing.JLabel lbluptomonth;
    private javax.swing.JTextField txtfather;
    private javax.swing.JTextField txtfees;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmonths;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpaidmonth;
    private javax.swing.JTextField txtsecurity;
    private javax.swing.JTextField txttotalamount;
    private javax.swing.JTextField txttotalfees;
    private javax.swing.JTextField txtuptomonth;
    // End of variables declaration//GEN-END:variables
}
