package student;


import connectivity.ConnectionProvider;
import home.HomePage;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ritesh Singh
 */
public class StudentLeaves extends javax.swing.JFrame {

    /**
     * Creates new form StudentLeaves
     */
    private void tableDetails()
    {
        DefaultTableModel dtm = (DefaultTableModel) tblabsentstudents.getModel();
        dtm.setRowCount(0);
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from leaves where status='Absent'");
            while (rs.next()) {
                String id = rs.getString(1);
                
                String room = "Not Found";
                Connection con1 = ConnectionProvider.getCon();
                Statement st1 = con1.createStatement();
                ResultSet rs1 = st1.executeQuery("select * from rooms");
                while (rs1.next()) {
                    String bed1 = " ", bed2 = " ", bed3 = " ", bed4 = " ";
                    if (rs1.getString(8) != null) {
                        bed1 = (String) rs1.getString(8);
                    }
                    if (rs1.getString(9) != null) {

                        bed2 = (String) rs1.getString(9);
                    }
                    if (rs1.getString(10) != null) {
                        bed3 = (String) rs1.getString(10);
                    }
                    if (rs1.getString(11) != null) {
                        bed4 = (String) rs1.getString(11);

                    }
                    if (bed1.equals(id) || bed2.equals(id) || bed3.equals(id) || bed4.equals(id)) {
                        room = (String) rs1.getString(1);
                    }
                }
                String name="",pmob="",mob="";
                Connection con2 = ConnectionProvider.getCon();
                Statement st2 = con2.createStatement();
                ResultSet rst2 = st2.executeQuery("select * from admission where std_id=" + id);
                while (rst2.next()) {
                    name=rst2.getString(2)+" "+rst2.getString(3);
                    pmob=rst2.getString(9);
                    mob=rst2.getString(12);
                }
                
                dtm.addRow(new Object[]{rs.getString(1), name, mob, pmob,room, rs.getString(2)});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public StudentLeaves() {
        initComponents();
        tableDetails();
        scallCross();
        scallBackground();
        scalltableBackground();
    }
    public final void scallBackground()
    {
        ImageIcon icon=new ImageIcon("C:\\Users\\rites\\OneDrive\\Documents\\NetBeansProjects\\HostelManagementSystem\\src\\images\\solid_5.jpg");
        Image img=icon.getImage();
        Image sImage=img.getScaledInstance(lblbackground.getWidth(), lblbackground.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon finalImage=new ImageIcon(sImage);
        lblbackground.setIcon(finalImage);
    }
    public final void scalltableBackground()
    {
        ImageIcon icon=new ImageIcon("C:\\Users\\rites\\OneDrive\\Documents\\NetBeansProjects\\HostelManagementSystem\\src\\images\\solid_5.jpg");
        Image img=icon.getImage();
        Image sImage=img.getScaledInstance(lbltableback.getWidth(), lbltableback.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon finalImage=new ImageIcon(sImage);
        lbltableback.setIcon(finalImage);
    }
    public final void scallCross()
    {
        ImageIcon icon=new ImageIcon("C:\\Users\\rites\\OneDrive\\Documents\\NetBeansProjects\\HostelManagementSystem\\src\\images\\Exit_big.png");
        Image img=icon.getImage();
        Image sImage=img.getScaledInstance(btnexit.getWidth(), btnexit.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon finalImage=new ImageIcon(sImage);
        btnexit.setIcon(finalImage);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblabsentstudents = new javax.swing.JTable();
        lblhead = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        lblid = new javax.swing.JLabel();
        btnapprove = new javax.swing.JButton();
        btnjoin = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        lbltableinfo = new javax.swing.JLabel();
        lblbackground = new javax.swing.JLabel();
        lbltableback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblabsentstudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Mobile Number", "Parents Mobile", "Room Number", "Absent From"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblabsentstudents);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 800, 290));

        lblhead.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        lblhead.setText("leave authorization section");
        getContentPane().add(lblhead, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 410, 40));

        txtid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 100, 30));

        lblid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblid.setText("Enter Student Id:");
        getContentPane().add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 130, 30));

        btnapprove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnapprove.setText("Approve Leave");
        btnapprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnapproveActionPerformed(evt);
            }
        });
        getContentPane().add(btnapprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 140, 30));

        btnjoin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnjoin.setText("Join Back");
        btnjoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjoinActionPerformed(evt);
            }
        });
        getContentPane().add(btnjoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, 30));

        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 70, 60));

        lbltableinfo.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        lbltableinfo.setText("The Following Table Shows The details of Students who are on Leave Now.");
        getContentPane().add(lbltableinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 580, 20));
        getContentPane().add(lblbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 460));

        lbltableback.setText("jLabel1");
        getContentPane().add(lbltableback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 800, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        HomePage.leave=true;
        //HomePage.obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnexitActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        setBounds(170,150, 800, 460);
    }//GEN-LAST:event_formWindowActivated

    private void btnapproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnapproveActionPerformed
    Connection con=ConnectionProvider.getCon();
    Date date=new Date();
    java.sql.Date sqldate=new java.sql.Date(date.getTime());
    String id=txtid.getText();
        try {
            PreparedStatement pst=con.prepareStatement("update leaves set from_date=?, status=? where student_id="+id);
            pst.setDate(1, sqldate);
            pst.setString(2,"Absent");
            pst.executeUpdate();
            tableDetails();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnapproveActionPerformed

    private void btnjoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjoinActionPerformed
    Connection con=ConnectionProvider.getCon();
    
    String id=txtid.getText();
        try {
            PreparedStatement pst=con.prepareStatement("update leaves set from_date=?, status=? where student_id="+id);
            Date date=new Date();
            java.sql.Date sqldate=new java.sql.Date(date.getTime());
            pst.setDate(1, sqldate);
            pst.setString(2,"Present");
            pst.executeUpdate();
            tableDetails();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnjoinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLeaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLeaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLeaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLeaves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentLeaves().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnapprove;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnjoin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JLabel lblhead;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lbltableback;
    private javax.swing.JLabel lbltableinfo;
    private javax.swing.JTable tblabsentstudents;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
